#!/bin/bash

# Record the MoltenVK GIT revision as a derived header file suitable for including in a build
set -eu
MVK_SOURCE_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MVK_GIT_REV="${MVK_SOURCE_REVISION:-$(git -C "${MVK_SOURCE_ROOT}" rev-parse HEAD 2>/dev/null || true)}"
if [[ ! "${MVK_GIT_REV}" =~ ^[0-9a-fA-F]{40}$ ]]; then
	MVK_GIT_REV="unknown"
fi
MVK_HDR_FILE="${BUILT_PRODUCTS_DIR}/mvkGitRevDerived.h"
MVK_HDR_TEMP="${MVK_HDR_FILE}.tmp"
printf '// Auto-generated by MoltenVK\nstatic const char* mvkRevString = "%s";\n' "${MVK_GIT_REV}" > "${MVK_HDR_TEMP}"
if cmp -s "${MVK_HDR_TEMP}" "${MVK_HDR_FILE}"; then
	rm "${MVK_HDR_TEMP}"
else
	mv "${MVK_HDR_TEMP}" "${MVK_HDR_FILE}"
fi
